app:
  name: "TalkSphere"
  mode: "dev"
  port: 8989
  version: "v1"

log:
  level: "debug"
  filename: "TalkSphere.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "forrest"
  password: "571400yst"
  db: "TalkSphere"
  max_open_connection: 20
  max_idle_connection: 10

redis:
  host: 127.0.0.1
  port: 16379
  password: ""
  db: 0
  pool_size: 100

encrypt:
  secret_key: "&12JsXXa@"

gin:
  mode: "debug"

snowflake:
  start_time: "2025-01-03"
  machine_id: 1

auth:
  jwt_expire: 8760

oss:
  bucket_name: "talkspere-1321722407"
  region: "ap-beijing"
  secret_id: "AKIDtfEZheOuCG8pLdlgOs9E5jARWO5LSL1T"
  secret_key: "HLCqGTSFpHTUHrFPQRGsGRRFrHUTO9j6"

default_avatar:
  avatar_url: "https://talkspere-1321722407.cos.ap-beijing.myqcloud.com/defaultAvatar.jpg"